let ebsDoktor = [
    majorsMinors(
        name: "Juhtimisteadus",
        level: .doctor,
        type: .sotsiaal,
        requirements: [
            Requirements(term: "CV"),
            Requirements(term: "Magistrikraad"),
            Requirements(term: "Doktoritöö kavand"),
            Requirements(term: "Motivatsioonikiri")],
        description: ["EBS doctoral programme in Management aims to broaden our understanding of the world by giving deep knowledge of organisational theories and society while developing critical and analytical thinking and research skills. Upon the successful competition of the programme, one has developed the ability to make continuous and logical arguments and synthesise new ideas. PhD degree in Management offers challenges and career opportunities in the academia as well as raises one’s value on the labour market.", "EBS PhD programme that focuses on the research of business, public and civil society organisations is the only doctoral programme in Management in Estonia and offers a comprehensive perspective on management and organisation studies. The programme is taught in English and has an international student body. On-going development activities and quality assurance of the programme is managed by the EBS Research and Development Council.", "The total volume of the programme is 240 ECTS, of which the studies give 60 ECTS and research activity 180 ECTS. Studies consist of compulsory and elective courses, doctoral/research seminars and teaching internship. The programme curriculum serves as a guideline for doctoral students, but each student has the right and obligation to put together an individual study plan. Research of the doctoral student is carried out according to individual study plan under the guidance of a supervisor. The progress of doctoral student is evaluated yearly by the evaluation committee formed by the EBS R&D Council.", "All doctoral students have an opportunity to go on exchange with the goal to pass part of their studies or conduct research in a foreign university. To exploit this opportunity is highly encouraged.", "The doctoral thesis presented to apply for the doctor’s degree may be in the form of an independent thesis, a series of publications provided with the summarising review article, or a published monograph."],
        outcomes: ["Õppekava läbinu:", "Omab laiapõhjalisi teadmisi ja süsteemset ülevaadet juhtimis- ja organisatsiooniteooriatest, organisatsioonide juhtimise õiguslikust ja majanduslikust keskkonnast", "Omab sügavaid ja ajakohaseid teadmisi juhtimisteaduse erinevates valdkondades", "Omab süsteemset ülevaadet sotsiaal- ja juhtumisuuringute metodoloogiast ning metoodilistest käsitlustest ja oskab teha põhjendatud valikuid nende kasutamisel erinevates valdkondades juhtimisprobleemide uurimisel", "Tunneb juhtimisteaduse erinevate valdkondade ja valdkondadevahelisi uurimismeetodeid ning oskab neid rakendada", "Oskab iseseisvalt ja kriitiliselt analüüsida, sünteesida ja hinnata uusi erialaspetsiifilisi ideid ja kontseptsioone ning loovalt ja teadusliku täpsusega identifitseerida ja formuleerida uurimis-teemasid", "Oskab algatada, kavandada, rakendada ja kriitiliselt hinnata uurimis- ja arendustöid, mis loovad uusi teadmisi ja rakenduslikke lahendusi", "Mõistab teaduse võimalusi ja piire, ühiskondlikku rolli ning vastutust teadustöö tulemuste avaldamisel ja kasutamisel", "Suudab analüüsida erinevate sotsiaalsete normide toimet ja hinnata nende mõju ja erisusi sotsiaalsete suhete reguleerimisel", "On võimeline suuliselt ja kirjalikult esitama ja argumenteerima oma uurimistööga seonduvaid probleeme, järeldusi ja nende aluseks olevaid teooriaid nii eriala asjatundjatele, kui ka erialavälistele inimestele inglise keeles", "Oskab iseseisvalt tegutseda mitmekülgses õpi-, töö- ja uurimiskeskkonnas rakendades omandatud juhtimis- ja meeskonnatöö oskusi", "Oskab identifitseerida uute teadmiste ja oskuste omandamise vajadusi ning toetada teiste õppimist ja erialast uurimuslikku tegevust ühiskonna muutuste kontekstis", "On võimeline edasi andma oma teadmisi õpetamise, juhendamise ning rakendus- ja tegevusuuringute või arendusprojektide juhtimise kaudu"],
        language: .inglise,
        majorWebsite: "https://ebs.ee/doctoral-studies",
        spots: 0,
        duration: 4,
        studyLocation: ["Tallinn"],
        eap: 240,
        cost: "2750€"
    )
]
