let ttüInter = [
    majorsMinors(
        name: "Arhitektuur",
        level: .integrated,
        type: .insener,
        requirements: [
            Requirements(term: "Matemaatika Riigieksam või TalTech Matemaatikakatse"),
            Requirements(term: "Eesti Keele Riigieksam"),
            Requirements(term: "Erialakatse")
        ],
        description: ["Soovid kujundada meid ümbritsevat linnaruumi ja tulevast elukeskkonda? Oled unistanud projekteerida kõrghooneid või disainida peensusteni läbimõeldud arhitektuurseid detaile? Sind huvitavad ruum, vorm ja valgus ning sooviksid siduda oma loomingulised ideed kaasaegsete innovaatiliste lahendustega? Kui nii, siis tule uuri lähemalt, mida TalTechi arhitektuuri erialal sinu tulevikule pakkuda on!", "Tallinna Tehnikaülikooli arhitektuuriõpe pöörab võrdselt tähelepanu nii loomingulisusele kui tugevatele praktilistele oskustele. Viieaastase õppe järel antakse sulle arhitektuurimagistri kraad. Õpingud koonduvad kolme stuudio ja kahe meistriklassi ümber. Nende raames teed mitmeid praktilisi töid, kus saad teoorias õpitut ellu rakendada.", "• Elamute projekteerimise stuudio projekte tehes saad praktikas kasutada teadmisi, mida oled õppinud ainetes nagu puit -ja kivikonstruktsioonid, tehnosüsteemid ja välistrassid.", "• Ühiskondlike hoonete projekteerimise stuudio projektid nõuavad sinult teadmisi teras- ja betoonkonstruktsioonide, ehitusakustika, energiatõhususe, sisekliima jm valdkondades.", "• Linnaehituse projektide stuudio raames tehtavaid töid toetavad näiteks linnaplaneerimise teooriad ja 21. sajandi linnaehituse arengusuunad, linna- ja eluasemesotsioloogia, ehitusõigus, keskkonnapoliitika ja liikluse erialaained."],
        outcomes: ["Lõpetajad on oodatud tööle nii suurtesse kui väikestesse arhitektuuri- ja projekteerimisbüroodesse. Riigiasutustes ning kohalikes omavalitsustes töötavad samuti arhitektid, kes tegelevad (näiteks linna) planeerimist ja ehitamist puudutavate küsimustega. Kogenud arhitektina võid aga tulevikus asutada oma büroo.", "Peale viieaastast õpet on sul Tallinna Tehnikaülikooli magistrikraad ning oled diplomeeritud arhitekt. Vastava tasemega spetsialist koostab ehitusprojekte siiski kogenuma arhitekti juhendamisel ega tee iseseisvalt otsuseid. Kui oled piisava töökogemuse saanud, on sul võimalik taotleda volitatud arhitekti kutset, kellel on luba omal vastutusel projekte kavandada.", "Pärast magistrikraadi saamist soovitame jätkata õpinguid doktorantuuris, sest doktorikraadi ja piisava töökogemusega on sul edaspidi võimalik taotleda volitatud arhitekti-eksperdi taseme kutsetunnistust. Volitatud arhitekt-ekspert on juba tippspetsialist, kes peale eelneva annab keerulisemaid eksperdihinnanguid ja osaleb rahvusvaheliste arhitektuurivõistluste žüriides."],
        language: .eesti,
        majorWebsite: "https://www.ttu.ee/sisseastujale/abituriendile/erialad/inseneriteaduskonna-erialad/arhitektuur/#ulevaade-11",
        spots: 0,
        duration: 5,
        studyLocation:  ["Tallinn"],
        eap: 300,
        cost: "0€"
    ),
    majorsMinors(
        name: "Ehitiste Projekteerimine ja Juhtimine",
        level: .integrated,
        type: .insener,
        requirements: [
            Requirements(term: "Matemaatika Riigieksam või TalTech Matemaatikakatse"),
            Requirements(term: "Eesti Keele Riigieksam")
        ],
        description: ["Ehitusinseneri töö on kodude ja töökohtade rajamine. Ehitiste projekteerimise ja ehitusjuhtimise eriala lõpetajana saad hakkama kõigega: väikeelamutest pilvelõhkujate ning keerukate tööstushooneteni. Kui sind tõmbab ehitusvaldkonna poole ja sulle meeldib näha oma mõtteid realiseerumas siis sellele erialale õppima tulek on kindel ja tulus investeering sinu tulevikku.", "Ehitus on maailma suurim majandusharu ja ehitusinseneri valikute mõju loodusele on märkimisväärne. Ehitatud keskkonna kujundamine on vastutusrikas töö, kuna hooned peavad olema vastupidavad ning ehitatud loodusressursse mõttetult raiskamata. Eesti vajab rohelise mõtteviisiga insenere.", "• Ehitiste projekteerimisele spetsialiseerumisel õpid süvendatult hoonete kandekonstruktsioone. Ainult kõige kõrgemate kutsetega spetsialistid võivad võtta vastutuse hoonete ja rajatiste projekteerimisel ning ehitamisel, kuna ehitusinseneri töö peab tagama inimeste turvalisuse, tervise ja mugavuse ehitatud keskkonnas. Õppetöö toimub Tallinna Tehnikaülikoolis Tallinnas.", "• Iga ehitusprojekt on ühtlasi investeerimisprojekt, mis algab eelseisvate kulude kalkuleerimisega ning ehitise tellijale eelarvete koostamisega. Lisaks insenerioskustele vajab iga ehitusprojekt teadmisi juhtimisstrateegiatest, juhtimispsühholoogiast, juriidikast ning kinnisvara ökonoomikast ja haldamisest. Seda kõike on võimalik õppida just ehitusjuhtimise spetsialiseerumissuunal. Õppetöö toimub Tallinna Tehnikaülikoolis Tallinnas.", "• Kuigi ühiskonna areng toob trendide muutudes ning vajaduste uuenedes kaasa üha moodsamate ja modernsemate ehitiste rajamise, on ajaloo seisukohalt äärmiselt vajalik ka vanade hoonete säilitamine ja taastamine. Ehitiste restaureerimise õpe valmistab ette ehitusinsenere, kes on võimelised rajama nii uusi ehitisi kui ka taastama eelnevate põlvkondade loodud väärtuslikke hooneid. Õppetöö toimub Tallinna Tehnikaülikooli Tartu kolledžis.", "• Projekteerimise ja arhitektuuri õppesuund ühendab endas nii inseneri kui arhitekti töö. Sinust saab loov insener, kes mõistab mõlema valdkonna väärtusi ning oskab neid teadmisi edukalt koos rakendada, et kujundada meile parem elukeskkond. Õppetöö toimub Tallinna Tehnikaülikooli Tartu kolledžis."],
        outcomes: ["Kui oled valinud spetsialiseerumiseks ehitiste projekteerimise suuna, leiad lõpetajana tööd näiteks mõnes projekteerimisbüroos või ehitusfirmas. Samuti võid vastutada suuremate ehitus- ja kinnisvaraprojektide arenduse eest või nõustada ehitushangete korraldamist. Kui sind kontoritöö eriti ei paelu, siis oled vägagi oodatud hoonete püstitamisega tegelevatesse ehitusettevõtetesse, kus saad juhtida reaalseid ehitustöid. Ka avalik sektor ehk ministeeriumid, linnad ja ametkonnad vajavad spetsialiste, kes korraldaksid ehituse valdkonda.", "Ehitusjuhtimisele spetsialiseerumine valmistab sind ette tööks ehitustööde juhina, ehituse eelarvestajana ja ökonomistina, ehituse tellijana, järelevalve insenerina või kinnisvara arendajana. Põhjalikult erinevaid ehitusmaterjale uurinud lõpetaja on oodatud ehitusmaterjalide tööstuses juhtivale positsioonile kvaliteedijuhiks, tootmisettevõtte juhiks, laboratooriumi juhatajaks või sarnasele vastutavale ametikohale. Võimalikud töökohad on ka riigiasutustes, mis on seotud ehitusmaterjalide tootmise juhtimise või kontrolliga.", "Ehitiste restaureerimise peaeriala lõpetajana oled sa ehitusinsener, kellel on lisaks ehitusalastele oskustele ka teadmised restaureerimisest, muinsuskaitse alustest ning arhitektuuriajaloost. Sinu tulevasteks tööandjateks on nii ehitus-, restaureerimis- ja projekteerimisfirmad kui ka kohalikud omavalitsused ja erinevad riigiasutused. Pärast lõpetamist ja ettenähtud töökogemuse omandamist saad muinsuskaitseametilt taotleda pädevustunnistust töötamaks ehitusmälestistel ja isegi UNESCO maailmapärandi nimekirja kuuluvatel objektidel.", "Ehitiste projekteerimise ja arhitektuuri peaeriala lõpetanuna oled ehitusinsener, kellel on lisaks teadmised arhitektuurist ning praktilised oskused erinevate hoonete projekteerimiseks ning esteetika eest vastutamiseks. Võid töötada iseseisvalt ehitusinsenerina või suuremates meeskondades koos disainerite, arhitektide ja teiste inseneridega. Ehitiste projekteerimise ja arhitektuuri suund on analoogne vastavate õppekavadega mitmetes Euroopa ülikoolides, näiteks Taani Tehnikaülikoolis, Praha Tehnikaülikoolis ja Edinburgh´i Ülikoolis."],
        language: .eesti,
        majorWebsite: "https://www.ttu.ee/teaduskond/inseneriteaduskond/",
        spots: 0,
        duration: 5,
        studyLocation: ["Tallinn", "Tartu"],
        eap: 300,
        cost: "0€"
    ),
    
    majorsMinors(
        name: "Hoonete Sisekliima ja Veetehnika",
        level: .integrated,
        type: .insener,
        requirements: [
            Requirements(term: "Matemaatika Riigieksam või TalTech Matemaatikakatse"),
            Requirements(term: "Eesti Keele Riigieksam")
        ],
        description: ["Ühe hoone sileda fassaadi all vonkleb sadu torusid, mis keerulisi süsteeme moodustades juhivad puhast vett sisse ja reovett välja, ventileerivad õhku ja reguleerivad temperatuuri. Need keerulised süsteemid tagavad, et inimesed üldse majades tegutseda ja tervislikult elada saaksid. Kas sulle meeldiks olla insener, kes oskab selliseid süsteeme projekteerida ning annab seeläbi hoonele elamisväärse sisu? Uuri lähemalt, mida hoonete sisekliima ja veetehnika erialal õpetatakse ning kes sinust saab!", "Hoonete sisekliima ja veetehnika õppimine annab sulle laiapõhjalised teadmised, kuidas hoonete tehnosüsteemid toimivad ja kuidas mõjutada hoonete energiatarbimist. Õpe hõlmab nii hoonete sisekliima tagamist kütte, jahutuse ja ventilatsiooniga kui ka veevarustuse, reovee ja keskkonnatehnikaga seotud teemasid.", "Koos üldiste insenerioskuste omandamisega saad oskused, kuidas kavandada hea sisekliimaga energiatõhusaid hooneid, mida pole võimalik saavutada ilma oskuslikult kavandatud, ehitatud ja hooldatud kütte-, ventilatsiooni- ning jahutussüsteemideta. Hoone tehnosüsteemide ja energiatõhususe arendamine on üks ehitussektori kiiremini arenevaid valdkondi.", "Vee ja keskkonnatehnika õppimine annab väga head teadmised sellest, kuidas saadakse tarbimiskõlbulik vesi ning kuidas see peale kasutamist keskkonda kahjustamata tagasi loodusesse juhitakse. Veevarustuse- ja kanalisatsiooniinsenerid on tegevad pea kõikide hoonete kavandamisel ja ehitamisel ning linnade ja asulate vee- ja reoveepuhastite, välisvõrkude planeerimisel, projekteerimisel, rajamisel ja uuendamisel."],
        outcomes: ["Linnastumise tõttu vajatakse eriala spetsialiste järjest rohkem. Puhta joogivee ja hästitoimivate vee- ja reovee puhastussüsteemide tagamine on tervisliku elukeskkonna säilimiseks esmatähtsusega. Hoonete sisekliima ja energiatõhususe parandamine on vältimatu, kui soovime võidelda kliimasoojenemisega ning tagada meeldiv ja tervislik keskkond nii toas kui ka õues. Lisaks uute hoonete ehitamisele tuleb vanu süsteeme rekonstrueerida ja olemasolevaid hooneid hooldada. Meie lõpetajad töötavad kesktaseme, tippjuhi või spetsialistina. Nad teostavad omanikujärelevalvet, on projekteerijad, ehitus-, objekti- või projektijuhid ning konsultandid. Meie vilistlaste stardipalk on suurem Eesti keskmisest palgast.", "Tuleviku tööandjatena võib nimetada suuri ehitusfirmasid nagu Merko, Astlanda, Nordecon, K-Projekt, Sweco või YIT, Uponor Eesti, PipeLife või ETSNord. Samuti vajatakse meie eriala spetsialiste, vee-ettevõtetes, näiteks AS Tallinna Vesi või AS Rakvere Vesi, avalikus sektoris Keskkonnaministeeriumis ja Keskkonnaametis ning kohalikus omavalitsuses.", "Hoonete tehnosüsteemide ehk kütte, ventilatsiooni ja jahutuse ning hoonesisese ja –välise veevarustuse ja kanalisatsiooni valdkonna spetsialistina on sinu töövõimalused järgnevad:", "Projekteerija ja konsultandi esmane ülesanne on osaleda hoonete kavandamise protsessis, et tagada nende toimimine ja energiatõhusus. Lisaks tuleb arvutada, kavandada ja kirjeldada projektis tehnosüsteemid, mille alusel need valmis ehitatakse", "Tehnosüsteemide ehitamine ja hoonete energiatõhusaks rekonstrueerimine", "Süsteemide rajamise järelevalve ülesandeks on teha kindlaks, et kõik süsteemid on välja ehitatud vastavalt projektile", "Seadmete ja materjalide müügitöö", "Süsteemide hoolduse ja häälestamise spetsialsti tööks on tehnosüsteemide hooldamine, parandamine ja seadistamine", "Tootearendaja tööks on paremini toimivate tehnosüsteemide komponentide välja arendamine ja katsetamine.", "Hoonete sisekliima ja veetehnika õppekaval kestab õpe viis aastat. Lõpetamisel saad magistrikraadi ja diplomeeritud veevarustus- ja kanalisatsiooni- ning kütte-, ventilatsiooni- ja jahutusinseneri esmakutse (7. tase). See tähendab, et tohid töötada vaid volitatud inseneri juhendamisel ega tee iseseisvaid otsuseid. Seetõttu soovitame esmase kutse tasandilt end edasi arendada volitatud veevarustus- ja kanalisatsiooniinseneriks, et saaksid iseseisvalt töötada keerukamate ja huvitavamate projektidega. Igal juhul tagab kutsestandardi omamine seda, et sinu teadmised ja oskused on võrdselt hinnatud nii siin kui seal pool piiri."],
        language: .eesti,
        majorWebsite: "https://www.ttu.ee/teaduskond/inseneriteaduskond/",
        spots: 0,
        duration: 5,
        studyLocation:  ["Tallinn"],
        eap: 300,
        cost: "0€"
    ),
    
    
    
    majorsMinors(
        name: "Teedeehitus ja Geodeesia",
        level: .integrated,
        type: .insener,
        requirements: [
            Requirements(term: "Matemaatika Riigieksam või TalTech Matemaatikakatse"),
            Requirements(term: "Eesti Keele Riigieksam")
        ],
        description: ["Võib öelda, et riigi majanduse aluseks on ennekõike infrastruktuur: teed, sillad, tunnelid, raudteed, lennujaamad ja sadamad, milleta ei pääse inimesed liikuma ega jõua kaubad tarbijani. Eesti teedevõrk on küll piisavalt tihe, kuid sellel ohutu ja sujuva liiklemise tagamine nõuab pidevat tööd. Infrastruktuur on ja jääb meie igapäevase toimetuleku esmaseks eelduseks.", "Kindel on, et hea haridusega insener leiab alati hea tasuga tööd, sest nii nagu Tallinn ei saa kunagi valmis, ei kao kunagi vajadus ehitusinseneride ja -geodeetide järele.", "Majanduse arengu tagab kaasaegse taristu olemasolu, mille üheks tähtsamaks osaks on piisava tihedusega ja heas seisukorras teedevõrk. Just sina võiksid olla uus teedeinsener. Teedeehituse ja geodeesia õppekavas saad valida kahe peaeriala vahel.", "Teedeehituse peaerialal saad omakorda spetsialiseeruda teedeehitusele või sillaehitusele. Teede- ja sillaehitus käsitlevad nende projekteerimist, ehitamist ning hooldamist, ehitustööde juhtimist, liikluskorraldust ja –ohutust ning teedevõrgu planeerimist.", "Ehitusgeodeesia valdkond tegeleb nii teede kui hoonete ehituses vajalike mõõdistustega, juba projekteeritud ehitise ja selle osade loodusesse märkimisega ning ehitise valmimisel ka jooksvate kontrollmõõdistustega."],
        outcomes: ["Alustava inseneri töötasu on üle Eesti keskmise, oma oskusi ja võimeid arendades on aga võimalik see üsna kiire ajaga kasvatada kahekordseks.", "Teede- ja sillaehituse eriala lõpetanuna on sul võimalus töötada järgmistel ametialadel:", "Teede- või sillaehitusprojektide planeerimine ja projekteerimine", "Teede- või sillaehituse juhtimine kõige erinevamatel tasemetel alates meistrist ehitusobjektil kuni ehitusfirma juhini", "Teede ja sildade korrashoid", "Ehitusjärelevalve", "Liiklusohutuse auditeerimine ja hindamine", "Kohalikes omavalitsustes teedeehituse tellija ülesandeid täitev spetsialist", "Inseneride koolitamine", "Ettevõtliku lõpetajana on sul võimalus luua oma ettevõte.", "Geodeedina oskad töötada mõõtetehnoloogiaga ning tead, mida teha olukorras, kui GPS meid aidata ei suuda (näiteks metsaaladel ning linnadžunglites). Samuti on sul vajalikud teadmised geoinformaatika, satelliittehnoloogia ja geograafiliste infosüsteemidega (GIS) seotud ülesannete lahendamiseks. Nii saad abiks olla hoopis teiste eluvaldkondade ülesannete lahendamisel nagu kliimamuutuste uurimine, Maa masside liikumine, maavärinate ennustamine jne.", "Sinu karjäärivõimalused on laiad, hõlmates nii geodeesiaettevõtteid, Maa-ametit ja teisi riigiasutusi, ehitusettevõtteid, kaardistusettevõtteid, ruumiandmetega seotud infrastruktuuri ettevõtteid kui ka ülikoole ning teadusasutusi. Geodeetide oskuste järele on vajadus suur - paljud meie üliõpilased on juba enne lõpetamist leidnud huvitava erialase töö!"],
        language: .eesti,
        majorWebsite: "https://www.ttu.ee/teaduskond/inseneriteaduskond/",
        spots: 0,
        duration: 5,
        studyLocation:  ["Tallinn"],
        eap: 300,
        cost: "0€"
    ),
]
