import SwiftUI

public extension Font {
    static let regularCallout = Font.callout.weight(.regular)
    static let regularBody = Font.body.weight(.regular)
    static let regularCaption = Font.caption.weight(.regular)
    static let regularTitle3 = Font.title3.weight(.regular)
    static let regularTitle2 = Font.title2.weight(.regular)
    static let regularTitle = Font.title.weight(.regular)
    static let regularSubHeadline = Font.subheadline.weight(.regular)
    static let lightCallout = Font.callout.weight(.light)
    static let lightCaption = Font.caption.weight(.light)
    static let lightTitle = Font.title.weight(.light)
    static let lightTitle2 = Font.title2.weight(.light)
    static let lightTitle3 = Font.title3.weight(.light)
    static let lightSubheadline = Font.subheadline.weight(.light)
    static let boldCaption = Font.caption.weight(.bold)
    static let boldCallout = Font.callout.weight(.bold)
    static let boldBody = Font.body.weight(.bold)
    static let boldTitle = Font.title.weight(.bold)
    static let boldTitle3 = Font.title3.weight(.bold)
    static let mediumTitle2 = Font.title2.weight(.medium)
    static let mediumTitle3 = Font.title3.weight(.medium)
    static let mediumBody = Font.body.weight(.medium)
    static let mediumCallout = Font.callout.weight(.medium)
    static let mediumSubHeadline = Font.subheadline.weight(.medium)
    static let semiBoldTitle3 = Font.title3.weight(.semibold)
    static let semiBoldTitle2 = Font.title2.weight(.semibold)
    static let semiBoldTitle = Font.title.weight(.semibold)
    static let semiBoldCallout = Font.callout.weight(.semibold)
    static let semiBoldBody = Font.body.weight(.semibold)
    static let semiBoldCaption = Font.caption.weight(.semibold)
    static let semiBoldSubHeadline = Font.subheadline.weight(.semibold)
    
}

