import SwiftUI

public extension Image {
    static let infoCircle = Image(systemName: "info.circle")
    static let info = Image(systemName: "info")
    static let flip = Image(systemName: "arrow.up.arrow.down")
    static let chevronRight = Image(systemName: "chevron.right")
    static let chevronLight = Image(systemName: "chevron.left")
    static let docs = Image(systemName:"doc.on.doc")
    static let magnifyingGlass = Image(systemName: "magnifyingglass")
    static let multiply = Image(systemName: "multiply")
    static let appLogo = Image("Õpi Eestis logo")
    static let appLogo2 = Image("estonia2")
    static let mappinEclipse = Image(systemName: "mappin.and.ellipse")
    static let person3 = Image(systemName: "person.3")
    static let person2 = Image(systemName: "person.2")
    static let person2Fill = Image(systemName: "person.2.fill")
    static let mappinCircle = Image(systemName: "mappin.circle")
    static let listDash = Image(systemName: "list.dash")
    static let chartBar = Image(systemName: "chart.bar")
    static let envelope = Image(systemName: "envelope")
    static let phone = Image(systemName: "phone")
    static let map = Image(systemName: "map")
    static let house = Image(systemName: "house")
    static let book = Image(systemName: "book")
    static let globe = Image(systemName: "globe")
    static let location = Image(systemName: "location")
    static let locationFill = Image(systemName: "location.fill")
    static let euro = Image(systemName: "eurosign.circle")
    static let euroFill = Image(systemName: "eurosign.circle.fill")
    static let squareStack = Image(systemName: "square.stack.3d.up.fill")
    static let clock = Image(systemName: "clock")
    static let clockFill = Image(systemName: "clock.fill")
    static let squareGrid = Image(systemName: "square.grid.3x2")
    static let thermometer = Image(systemName: "thermometer")
    static let doc = Image(systemName: "doc.text")
    static let requirements = Image(systemName: "person.crop.circle.badge.checkmark")
    static let outcomes = Image(systemName: "briefcase")
    static let graduationFill = Image(systemName: "graduationcap.fill")
    static let graduation = Image(systemName: "graduate")
    static let link = Image(systemName: "link")
    static let stack = Image(systemName: "square.3.stack.3d")
}
