let sisekaitseAkadeemiaKutse = [
    majorsMinors(
        name: "Politseiametnik",
        level: .kutseharidus,
        type: .Politseijapiirivalvekolledž,
        requirements: [
            Requirements(term: "Eesti kodakondsus"),
            Requirements(term: "Keskharidus"),
            Requirements(term: "Laitmatu taust"),
            Requirements(term: "Vastuvõtukatse"),
            Requirements(term: "Vestlus"),
            Requirements(term: "Kehalised katsed")],
        description: ["Politseiametniku eriala õppekava on väga praktilise suunitlusega andes õppuritele vajalikud teadmised, oskused ja hoiakud, mis võimaldavad eriala lõpetajal töötada Politsei- ja Piirivalveametis patrullpolitseiniku või piirivalvurina.  Soovijad saavad politseiametniku kutseõppe käigus läbida valikmooduli  Merel ja piiriveekogul otsingu- ja päästetööde läbiviimine ning sooritada piirivalvuri kutsetunnistuse saamiseks kutseeksami."],
        outcomes: ["Õppekava läbinud õppija:", "Mõistab oma vastutust enesearendamisel, otsib ja kasutab õppimisvõimalusi, lähtudes elukestva õppimise põhimõtetest", "Arvestab tagasisidega, analüüsib ennast ja oma töö tulemusi ning muudab vastavalt oma käitumist", "Tegutseb vastutustundlikult, töötab iseseisvalt ja teeb vajadusel koostööd ning juhindub oma tegevuses politseiorganisatsiooni põhiväärtustest, ametniku eetika normidest ja õigusaktidest", "Tunneb elulises juhtumis ära politsei sekkumist vajava olukorra, kasutab probleemi lahendamisel sobivaid korrakaitselisi meetmeid ning tegutseb turvaliselt ja eesmärgipäraselt, valides sekkumiseks asjakohased meetodid ja vahendid", "Kontrollib isikute ja transpordivahendite liikumist piiripunktis, deklareerimist vajava kauba olemasolu, veesõidukite liiklemist merel ja piiriveekogudel ning reisi ja transpordivahendite dokumente piiripunktis, kasutades asjakohaseid meetodeid ja vahendeid", "Tunneb elulises juhtumis ära süüteo tunnused, alustab väärteomenetluse, viib läbi väärteomenetluse ja määrab vajadusel isikule karistuse või alustab kriminaalmenetluse ja viib läbi esmased menetlustoimingud", "Koostab ja vormistab korrektseid dokumente ja tekste, kasutab tööks vajalikke info ja kommunikatsioonitehnoloogia vahendeid ning erialaseid infosüsteeme, järgides andmekaitse nõudeid", "Valdab multikultuurses keskkonnas töötamiseks vajalikke suhtlemisoskusi, lahendab probleeme iseseisvalt ja meeskonnaliikmena", "Mõtleb süsteemselt ja loovalt ning oskab oma ideid kriitiliselt hinnata ja planeerida oma karjäärivõimalusi Politsei- ja Piirivalveametis", "Kasutab eesti keelt tasemel C1, vene keelt tasemel A2 ja inglise keelt tasemel A2."],
        language: .eesti,
        majorWebsite: "https://www.sisekaitse.ee/et/vastuv6tt_politseiametnik",
        spots: 50,
        duration: 1.5,
        studyLocation:  ["Tallinn"],
        ekap: 100,
        cost: "0€"
    ),
    majorsMinors(
        name: "Vanglaametnik",
        level: .kutseharidus,
        type: .justiitskolledž,
        requirements: [
            Requirements(term: "Eesti kodakondsus"),
            Requirements(term: "Keskharidus"),
            Requirements(term: "Laitmatu taust"),
            Requirements(term: "Eesti keele oskus vähemalt C1 tasemel"),
            Requirements(term: "Vastuvõtukatse"),
            Requirements(term: "Vestlus"),
            Requirements(term: "Kehalised katsed")],
        description: ["Vanglaametniku erialal omandatakse hea ettevalmistus töötamiseks vanglas valvuri või vanemvalvuri ametikohal. Vanglaametnikel on politseinike ja kohtuametnike kõrval tähtis roll riigi õiguskaitsesüsteemis. Vanglateenistus, kuhu eriala lõpetanu tööle asub, väärtustab erialase hariduse saanud isikuid, näiteks suurendades erialase kvalifikatsiooni tõusu alusel töötasu kuni kolmandiku võrra."],
        outcomes: ["Õppekava läbimisel õpilane:", "Täidab tööülesandeid II klassi valvuri ametiastmel olevatel ametikohtadel", "Väärtustab organisatsiooni traditsioone ja hoiab kõrgel oma ametiau", "Suhtub sallivalt hoiakute ja väärtuste erisustesse", "Mõistab meeskonnatöö vajalikkust ning suhtleb meeskonnakaaslastega korrektselt", "Suhtleb õpitavas võõrkeeles algtasemel", "Kasutab erialaseid teadmisi ja kogemusi oma elukvaliteedi tõstmiseks ja isiksuse arendamiseks", "Ilmutab valmisolekut elukestvaks õppeks."],
        language: .eesti,
        majorWebsite: "https://www.sisekaitse.ee/et/vastuv6tt_vanglaametnik",
        spots: 60,
        duration: 1,
        studyLocation:  ["Tallinn"],
        ekap: 60,
        cost: "0€"
    ),
    majorsMinors(
        name: "Päästekorraldaja",
        level: .kutseharidus,
        type: .Päästekolledž,
        requirements: [
            Requirements(term: "Eesti kodakondsus"),
            Requirements(term: "Keskharidus"),
            Requirements(term: "Vastuvõtukatse"),
            Requirements(term: "Vestlus")],
        description: ["Päästekorraldaja erialal õpitakse vastu võtma ja menetlema 112 numbrile saabuvaid hädaabikõnesid. Kuna päästekorraldaja tegeleb igapäevaselt erineva emakeelega kõnelejate hädaabiteadetega, on õppekavas oluline roll keeleõppel (eriti vene keelel), suhtlemiseoskuste arendamisel ja kultuuride tundmisel. Eriala edukalt lõpetanud saavad tööd Häirekeskuse piirkondlikes keskustes Tallinnas, Tartus, Jõhvis ja Pärnus."],
        outcomes: ["Oskab iseseisvalt vastu võtta ja töödelda hädaabiteateid, täidab uudseid lahendusi eeldavaid tööülesandeid, langetab otsuseid ja vastutab oma tööülesannete täitmise eest", "Oskab kasutada info- ja kommunikatsioonivahendeid ning erialaseid andmebaase", "Väärtustab organisatsiooni traditsioone ja hoiab kõrgel oma ametiau", "Järgib suhtlemise ning klienditeeninduse põhimõtteid", "Suhtub sallivalt hoiakute ja väärtuste mitmekesisusse", "Kasutab riigikeelt tasemel C1, vene keelt osaoskuste mõistmise ja rääkimise osas tasemel B1", "Kasutab arvutit tasemel AO1-AO12."],
        language: .eesti,
        majorWebsite: "https://www.sisekaitse.ee/et/vastuv6tt_p22stekorraldaja",
        spots: 20,
        duration: 1,
        studyLocation:  ["Tallinn"],
        ekap: 60,
        cost: "0€"
    ),
]
